service: multi-region-lambda function

frameworkVersion: '2'

plugins:
  - serverless-high-availibity-multi-region

custom:
  dns:
    hostedZoneId: ABCDEF ## UPDATE
    domainName: multiregion-docker-${opt:stage, 'dev'}.test.com ## UPDATE
    healthCheckResourcePath: healthcheck
    us-west-1:
      acmCertificateArn: arn:aws:acm:us-west-1:ABCDEF:certificate/12345 ## UPDATE
      failover: PRIMARY
    us-east-1:
      acmCertificateArn: arn:aws:acm:us-east-1:ABCDEF:certificate/12345 ## UPDATE
      failover: SECONDARY

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  multiregion:
    handler: handler.multiRegion
    events:
      - http:
            path: region
            method: get
      - http:
            path: healthcheck
            method: get